name: CI Workflow

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    env:
      PUSHER_JWT_SIGNER_SECRET: secret
      PUSHER_PORT: 4000
      PUSHER_CONTROL_SECRET: "other secret"
      PUSHER_HOSTNAME: http://example.com

    strategy:
      matrix:
        otp-version: ['27']
        elixir-version: ['1.18']

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Erlang and Elixir
      uses: erlef/setup-beam@v1
      id: setup-beam
      with:
        otp-version: ${{ matrix.otp-version }}
        elixir-version: ${{ matrix.elixir-version }}

    - name: Restore dependencies and _build
      uses: actions/cache/restore@v3
      with:
        key: mix-${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-${{ hashFiles('mix.lock') }}
        path: |
          _build
          deps
        restore-keys: |
          mix-${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-
          mix-${{ steps.setup-beam.outputs.otp-version }}-
          mix-

    - name: Download and compile dependencies
      run: |
        mix deps.get
        mix deps.compile

    - name: Check formatting and compile
      run: |
        mix compile --warnings-as-errors

    - name: Cache dependencies and _build
      uses: actions/cache/save@v3
      with:
        key: mix-${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-${{ hashFiles('mix.lock') }}
        path: |
          _build
          deps

    - name: Run tests
      run: |
        mix test
